import Link from "next/link";
import { getLists } from "@/lib/data";
import { daysRemaining, deadlineLabel, formatDateBR } from "@/lib/date";

export default function ListsPage() {
  const lists = getLists();
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-teal-700">Gerenciamento</p><h1 className="mt-1 text-3xl font-black">Listas de encomendas</h1><p className="mt-2 text-sm text-slate-600">Cadastre, edite e acompanhe cada chegada de mercadoria.</p></div><Link href="/admin/listas/nova" className="btn btn-primary">+ Nova lista</Link></div><div className="grid gap-4 lg:grid-cols-2">{lists.map((list) => { const days = daysRemaining(list.return_date); return <article key={list.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="text-lg font-extrabold">{list.title}</h2>{list.status === "ARQUIVADA" && <span className="badge bg-slate-100 text-slate-600">Arquivada</span>}</div><p className="mt-1 text-sm text-slate-500">{formatDateBR(list.arrival_date)} → {formatDateBR(list.return_date)}</p></div><span className={`badge ${days < 0 ? "bg-red-50 text-red-700" : days <= 2 ? "bg-amber-50 text-amber-700" : "bg-teal-50 text-teal-700"}`}>{deadlineLabel(days)}</span></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Box value={list.total_recipients} label="Total"/><Box value={list.pending_recipients || 0} label="Pendentes"/><Box value={list.received_recipients || 0} label="Recebidos"/></div><div className="mt-4 flex gap-2"><Link href={`/admin/listas/${list.id}`} className="btn btn-primary flex-1">Abrir lista</Link><Link href={`/admin/listas/${list.id}/editar`} className="btn btn-secondary">Editar</Link></div></article>; })}{lists.length === 0 && <div className="card col-span-full p-10 text-center"><div className="text-4xl">📦</div><h2 className="mt-3 text-lg font-black">Nenhuma lista cadastrada</h2><p className="mt-2 text-sm text-slate-600">Cadastre a primeira chegada de mercadorias.</p></div>}</div></div>;
}
function Box({value,label}:{value:number;label:string}) { return <div className="rounded-xl bg-slate-50 p-3"><div className="text-lg font-black">{value}</div><div className="text-xs text-slate-500">{label}</div></div>; }
